### ISSUE TITLE
Default translation

### ISSUE THREAD

**Issue by I-NOZex** [2amigos/yii2-translateable-behavior#13]
It would be nice if it was possible to define a default translation in case of missing
Eg: My site is in 'pt-pt' but I have only translations in 'en-gb'... i think is preferible see the info in another language, than no info at all...
Thank you!

**Comment by I-NOZex** [comment]
For anyone with same troubble, this was the way I work-arround it:
```
    public function afterFind(){
        parent::afterFind();

        $translateableFields = $this->getAttributes( $this->translationAttributes  );
        $requestLang = $this->getLanguage();
        foreach($translateableFields as $attrName => $value){
            if( empty($value) ){
                $this->setLanguage('pt-PT');
                $fallbackValue = $this[$attrName];
                $this->setLanguage($requestLang);
                $this[$attrName] = $fallbackValue;
            }
        }
    } 
```

But again, it would be nice if the Behavior it self provide such functionality.
Thank you.

**Comment by tonydspaniard** [comment]
Fallback has been added by #15
