### ISSUE TITLE
Bug when applying limit on query

### ISSUE THREAD

**Issue by I-NOZex** [2amigos/yii2-translateable-behavior#14]
I'm using the **2amigos/yii2-translateable-behavior**,  and when I limit the query set (aka, use _per-page_ parameter), the query is returning all translations of records that match the query criteria.

Let me try explain this better, imagine the following scenario:
I have the table ARTICLE, each article can have one or more translations, stored in  ARTICLE_LANG table.
I want to return the first 5, if those five only have 1 translation (meaning, original language), I will receive 5 unique records.
Now, imagine this twist, where  those 5 records, the 2 first records have 2 translations each, what the query will return is 4 records corresponding to the first two, and the fifth will be ARTICLE no.3

That makes the api return only 3 unique records, instead of the 5 I've requested. 
@tonydspaniard

**Comment by I-NOZex** [comment]
I worked arroud it, changing my SearchModel this way:

```php
        $query->andFilterWhere([
            'id' => $this->id,
            'lang_id' => \Yii::$app->language //added this condition
        ]);
```

**Comment by tonydspaniard** [comment]
Glad you found the solution @I-NOZex

**Comment by I-NOZex** [comment]
No problem, keep the good work 🙂
