### ISSUE TITLE
translationAttributes requires language attribute

### ISSUE THREAD

**Issue by SOHELAHMED7** [2amigos/yii2-translateable-behavior#19]
Assumption

I have same schema as 
https://github.com/2amigos/yii2-translateable-behavior#preparation

this is behavior config in tour model
```php
public function behaviors()
{
    return [
        'trans' => [ // name it the way you want
            'class' => TranslateableBehavior::className(),
            // in case you named your relation differently, you can setup its relation name attribute
            // 'relation' => 'translations',
            // in case you named the language column differently on your translation schema
            // 'languageField' => 'language',
            'translationAttributes' => [
                'title', 'description'
            ]
        ],
    ];
}
```

Now when i save model in actionCreate as
```php
$tour_model->lang = 'en';
```

getting error 
> yii\base\UnknownPropertyException: Setting unknown property: 
\models\Tour::lang in ...

now i add a lang in behavior as 
```php
'translationAttributes' => [
                'title', 'description', 'lang'
            ]
```

and having below line in controller, all works fine
```php
$tour_model->lang = 'en';
```

Is this a issue or doc should be updated?
I think the doc should be updated that `lang` att should also be in translationAttributes

feel free to ask more details if needed

**Comment by cebe** [comment]
> $tour_model->lang = 'en';

the language field should be `language` not `lang`, so you should call `$tour_model->language = 'en';` instead.
