### ISSUE TITLE
Cannot make PR

### ISSUE THREAD

**Issue by nolka** [2amigos/yii2-translateable-behavior#21]
Please, update permissions to repo)

**Comment by cebe** [comment]
you do not need special permissions for creating a pull request.
see github help for instructions: https://help.github.com/en/articles/creating-a-pull-request

**Comment by nolka** [comment]
![изображение](https://user-images.githubusercontent.com/321107/55498633-50976080-566e-11e9-84c0-bc2e6921942b.png)

**Comment by tonydspaniard** [comment]
@nolka you re trying to push to master and that is not allowed. Please, fork the repo, make the changes you wish to do and then create a pull request as described by @cebe 

Thank you to try to help us and using the widget.
