### ISSUE TITLE
Search on ID in default GridView gives SQL error

### ISSUE THREAD

**Issue by nagyt234** [2amigos/yii2-translateable-behavior#5]
I get the following SQL error on search on the ID field:
```
Integrity constraint violation – yii\db\IntegrityException
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
The SQL being executed was: SELECT COUNT(*) FROM `re_ingredient_group` LEFT JOIN `re_ingredient_group_lang` ON `re_ingredient_group`.`id` = `re_ingredient_group_lang`.`ingredient_group_id` WHERE (`id`='1') AND (`re_ingredient_group_lang`.language='en-US')

Error Info: Array
(
    [0] => 23000
    [1] => 1052
    [2] => Column 'id' in where clause is ambiguous
)

Caused by: PDOException
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
```
The error is quite clear, the ID field in the where clause is not qualified by the table name. Any idea how to achieve, that the fully qualified field name is used?

**Comment by tonydspaniard** [comment]
Try to use table names at all times. Yii adds a table alias for its current model as: `t`, but you could easily add the `tableName.id` prefix. I know is a pain, but would solve your issues with it. I believe that Yii should avoid that conflict automatically but is not happening and its a personal opinion.

**Comment by thecortex** [comment]
Could there be a method in ActiveQuery such that we can enforce custom aliases? For example,
MyModel::find()->as('mm_alias')->all();
