### ISSUE TITLE
Updating doesn't work

### ISSUE THREAD

**Issue by allesan** [2amigos/yii2-translateable-behavior#7]
I've installed this great extension and everything works fine with displaying data already in database.
But when i try to update data nothing happens. As far I can see, title property never gets marked as dirty and so never gets updated. I have Article and ArticleTranslation models setup up as by instructions.
This is in my activeForm among other fields.

```<?= $form->field($model, 'title')->textInput() ?>```

**Comment by tonydspaniard** [comment]
How did you set your rules?

**Comment by allesan** [comment]
In Article.php model I have ['title', 'slug', 'content'] required (among few other fields).
And also [['title', 'slug', 'content'], 'string']

**Comment by allesan** [comment]
It was my mistake.
There was one attribute in the required that should not be there.
And I have found getErrors()
