### ISSUE TITLE
Validation error at saving translation remains hidden.

### ISSUE THREAD

**Issue by nagyt234** [2amigos/yii2-translateable-behavior#8]
I have the following validation in model `IngredientGroupLang`:

```
    public function rules()
    {
        return [
            [['ingredient_group_id', 'language', 'name'], 'required'],
            [['ingredient_group_id'], 'integer'],
            [['language', 'name'], 'string', 'max' => 255],
            [['language', 'name'], 'unique', 'targetAttribute' => ['language', 'name']],
        ];
    }
```

Uniqueness validation error of `IngredientGroupLang` at saving of an instance of  `IngredientGroup` remains hidden, what causes that the`IngredientGroup` will be saved without `IngredientGroupLang` record, causing an inconsistent database. Even if I overwrite the `save` method of  `IngredientGroup` to run in transaction, it does not help, because I can not catch the validation error of the translation.

I think, the problem is, that validation error at saving the translation should raise an exception and the validation error should be bubbled up into the main model instance. The exception could than be catched.

Do you have any idea? I need a uniqueness validation on the name attribute.

**Comment by I-NOZex** [comment]
this still unsolved

**Comment by tonydspaniard** [comment]
What do you think @schmunk42 and @cebe if bubbling up the error is the right way to solve this issue, I will add it to the library.

**Comment by cebe** [comment]
beforeValidate() could be implemented in the translation model and add the errors to the main model. Translation models should internally only be saved with save(false) then.

**Comment by tonydspaniard** [comment]
Thanks @cebe
